version: '3.7'

services:
  task-manager:
    env_file:
    - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - .:/app
      - /app/node_modules
    container_name: task-manager
    expose:
      - '3030'
    ports:
      - '3030:3030'
    command: pnpx prisma generate && pnpm dev
    
  prisma-postgres-api:
      stdin_open: true
      command: pnpx prisma generate
      build:
        context: .
        dockerfile: Dockerfile
      container_name: prisma-postgres-api
      depends_on:
        - postgres
      ports:
        - "3000:3000"
      restart: always
